### ISSUE TITLE
Repository.watchersCount is same as Repository.stargazersCount

### ISSUE THREAD

**Issue by omegaui** [SpinlockLabs/github.dart#310]
![Screenshot from 2022-06-09 12-40-09](https://user-images.githubusercontent.com/73544069/172786993-1fe37f0e-197a-4fe5-b640-ca503bd63efe.png)

I am currently writing a view only dashboard in Flutter using this amazing library,
While implementing the Repo-Info part, I found out that the `Repository.watchersCount` is exactly the same as `Repository.stargazersCount`.

**Comment by robrbecker** [comment]
@omegaui after some quick googling, this isn't an issue with this library. It is intended behavior from the Github API. In the past you could watch a repo. It was renamed to starring. In order to prevent breaking applications, the new field was added and the old was left. They are the same thing though.
See https://github.community/t/bug-watchers-always-same-as-stargazers-count-in-api-user-starred/14224 for the official response.
