### ISSUE TITLE
Use http package

### ISSUE THREAD

**Issue by marcojakob** [SpinlockLabs/github.dart#34]
We should probably use the [http package](https://pub.dartlang.org/packages/http) on pub which provides some high-level functions and classes to consume HTTP resources.

This might make the classes `http/client.dart`, `http/request.dart`, and `http/response.dart` superfluous.

**Comment by stevenroose** [comment]
Hmm. Sad that using the current approach, all packages depending on this package also need to split up into server and browser versions. That's why the http package was made in the first place.

I did the same for [WebSockets](https://github.com/stevenroose/dart-websockets). It uses reflectable instead of mirrors which reduced code size significantly, but requires browser users to add a transformer to their pubspec.yaml. I opened [this issue](https://github.com/dart-lang/sdk/issues/26475) recently in the hope the Dart folks improve mirrors in the future. I have the required transformer and I'm sad to see members of the Dart team suggest developers to "use reflectable instead of mirrors".

So, to round up, I'm in favor of using http because it makes the library more platform-agnostic (just have `new Github(Client client)` without all the http code).
